import { watch, FSWatcher } from 'chokidar';
import { RavenLogger } from './logger.js';
import { RavenEngine } from './engine.js';
import { RavenConfig } from './config.js';

/**
 * Raven-Os File Watcher (V4 - PERFECT SHIELD)
 * 
 * This watcher is designed with multi-layered isolation to prevent 
 * catastrophic internal loops in monorepos. 
 */
export class RavenWatcher {
  private watcher?: FSWatcher;
  private debounceTimer?: any;

  constructor(private config: RavenConfig, private engine: RavenEngine) {}

  /**
   * Start watching files and trigger rebuilds
   */
  start(onRebuild: (path: string) => Promise<void>) {
    const watchPaths = [
      this.config.appsDir,
      this.config.packagesDir,
    ];

    RavenLogger.info(`[WATCHER] Monitoring changes in: ${watchPaths.join(', ')}`);

    // PERFECT SHIELD: High-precision exclusion regex for absolute paths
    const ignoredPatterns = [
      /(^|[\/\\])\../,                     // Dotfiles
      /[\\/](node_modules|dist|\.raven|android|ios|\.git)[\\/]/, // Build & Dependency artifacts
      /\.map$/,                            // Source maps (often changed by bundlers)
      /metafile\.json$/,                   // Metadata generated by esbuild
      /index\.css$/,                       // Build outputs specifically
      /index\.js$/,                        // Build outputs specifically
    ];

    this.watcher = watch(watchPaths, {
      ignored: ignoredPatterns,
      persistent: true,
      ignoreInitial: true,
      // Stability: ensure file isn't being written when we catch it
      awaitWriteFinish: {
        stabilityThreshold: 150, 
        pollInterval: 100
      }
    });

    this.watcher.on('change', (path: string) => {
      // 1. Debounce Layer (V25 - Increased to 400ms for total safety)
      if (this.debounceTimer) clearTimeout(this.debounceTimer);
      
      this.debounceTimer = setTimeout(async () => {
        RavenLogger.info(`[WATCHER] Stable Change detected: ${path}`);
        
        try {
          await onRebuild(path);
          RavenLogger.success(`[WATCHER] Rebuild complete.`);
        } catch (err: any) {
          RavenLogger.error(`[WATCHER] Rebuild failed`, err.message);
        }
      }, 400); 
    });
  }

  stop() {
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
      this.debounceTimer = undefined;
    }
    this.watcher?.close();
  }
}
